install bazaar
install brew-cask
install ctags
install elasticsearch
install ffmpeg
install git
install git-extras
install git-flow
install go
install go-app-engine-64
install htop-osx
install iftop
install imagemagick
install macvim
install mercurial
install mongodb
install mysql
install nginx
install node
install packer
install pdf2image
install pidof
install postgresql
install psgrep
install rabbitmq
install reattach-to-user-namespace
install redis
install siege
install ssh-copy-id
install the_silver_searcher
install tmux
install tmux-mem-cpu-load
install three
install vim
install wget
install zsh
cleanup
doctor
