- hosts: localhost
  become: true
  gather_facts: yes
  connection: local

  tasks:
    - name: Install packages
      apt:
        name:
          - htop
          - curl
          - git
          - neovim
          - jq
          - tree
          - watch
          - silversearcher-ag
          - direnv
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes



