- hosts: localhost
  become: true
  tasks:
    - name: Install packages
      apt:
        pkg:
          - htop
          - curl
          - git
          - neovim
        update_cache: yes
        cache_valid_time: 3600

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
